[package]
name = "para-bthome"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.8.0"
defmt = { version = "1", optional = true }
para-fmt = { path = "../para-fmt" }

[features]
defmt = ["dep:defmt", "heapless/defmt-03", "para-fmt/defmt"]
